### ISSUE TITLE
Add percentage to slider

### ISSUE THREAD

**Issue by niklasr22** [niklasr22/BrightIntosh#112]
A percentage indicator could be great too. When you find the 'sweet' spot you can always set it to that setting. Now it's just a slider with no information

_Originally posted by @whitespacecode in https://github.com/niklasr22/BrightIntosh/discussions/89#discussioncomment-8824401_

**Comment by niklasr22** [comment]
A macOS style brightness slider with an indicator inside would be the best solution.

**Comment by waydabber** [comment]
Hi there, I created a macOS Control Center style slider that can be used with Cocoa, it's available open source in MonitorControl - feel free to use/reuse it or the technique involved!

[SliderHandler.swift](https://github.com/MonitorControl/MonitorControl/blob/main/MonitorControl/Support/SliderHandler.swift)

Let me know if you need any help with it! :)

**Comment by niklasr22** [comment]
@waydabber Thank you, that's very nice! I will look into it.
