### ISSUE TITLE
Distribution via homebrew

### ISSUE THREAD

**Issue by seyfeb** [niklasr22/BrightIntosh#120]
Are there any plans to distribute the releases via homebrew? I'd very much appreciate using homebrew as a way to manage installed software ;)

Thanks for your invested time and work!

**Comment by niklasr22** [comment]
Hi, I'm glad you like BrightIntosh.
Until recently we distributed BrightIntosh through brew, but we switched to a paid App Store distribution only as the costs of a free distribution couldn't be covered by donations.
