### ISSUE TITLE
Your build script failed (award)

### ISSUE THREAD

**Issue by SUPERCELLEX** [niklasr22/BrightIntosh#126]
v1.6.2 doesn't have a binary, either this is intentional or CI died somewhere

**Comment by SUPERCELLEX** [comment]
Update, I tried it
Yeah no your tests are failing it doesn't even execute 
<img width="734" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/44790931/e790279c-5344-45b2-b8e3-d27aa4dcddac">

**Comment by niklasr22** [comment]
The reason for the missing executable is explained [here](https://github.com/niklasr22/BrightIntosh/issues/120#issuecomment-2054137110).
What commands did you run to receive this output/error?

**Comment by SUPERCELLEX** [comment]
Built through Xcode

**Comment by SUPERCELLEX** [comment]
Unclose this, building through Archive fails too. Silently.

**Comment by SUPERCELLEX** [comment]
Might be my signing
