### ISSUE TITLE
How to delete everything

### ISSUE THREAD

**Issue by Gea97** [niklasr22/BrightIntosh#128]
Hi, my BrightIntosh broke today, I can't use the shortcuts anymore, but it works fine on my gf computer, so it's an isolated case, my question is how do I uninstall the program? (to do a new clean installation)

I noticed that even after I delete and reinstall the application my shortcut and preferences remains, so I figured that I have to remove something else, but I don't know what to remove, I don't seem to find anything in /Library

**Comment by niklasr22** [comment]
Hi, sorry to hear that. Settings should be stored at `~/Library/Containers/de.brightintosh.app/Data/Library/Preferences/de.brightintosh.app.plist`. This is because the app runs in a sandbox.
Maybe you should delete the entire `de.brightintosh.app` directory from `~/Library/Containers`.
Let me know if this solves your problem.

**Comment by Gea97** [comment]
> Hi, sorry to hear that. Settings should be stored at `~/Library/Containers/de.brightintosh.app/Data/Library/Preferences/de.brightintosh.app.plist`. This is because the app runs in a sandbox. Maybe you should delete the entire `de.brightintosh.app` directory from `~/Library/Containers`. Let me know if this solves your problem.

Yes it solved my problem thanks!

The only thing is that if I use the shortcuts to update the brightness then the slider remains stuck, is this expected behaviour? I don't remember if it was always the case.

I mean, I can still update the brightness with the slider, but the slider doesn't move if I use the shortcuts.

**Comment by niklasr22** [comment]
I'm glad it worked.
That's a bug, thanks for reporting it!
