### ISSUE TITLE
Brightness reverts to normal, ie app doesn't work!

### ISSUE THREAD

**Issue by aronbarcelona** [niklasr22/BrightIntosh#151]
I'm on an M1 16 inch. I was having this issue previously – when I enabled Brightintosh it would briefly flash bright then revert to normal brightness. The overlay method fixed this for me. Since the overlay method has been removed the app has stopped working...

**Comment by aronbarcelona** [comment]
Just tried turning Flux off and this fixes the bug. (Even though it's daytime so flux shouldn't be changing anything!) May be useful to add a word of warning somewhere.

**Comment by niklasr22** [comment]
This issue popped up already [here](https://github.com/niklasr22/BrightIntosh/issues/104). I think that even when flux doesn't do anything obvious during daytime it still controls gamma values of the screen which conflict with BrightIntosh. Maybe I will add some information about this somewhere.
