### ISSUE TITLE
Not compatible with Macbook Pro M1

### ISSUE THREAD

**Issue by drjohnf** [niklasr22/BrightIntosh#152]
Software did not have a description on the Apple Store about incompatibility with later model Macs....actually quite the opposite was implied, so I paid for the software but was unable to use it.  Is there a solution for a MBP M1 running 14.4.1 (23E224)?

I'm not worried about the wasted money - you're trying to do a good thing and I have a huge amount of respect for people trying to make open source software - so I don't want a refund....just perhaps some information on which Macs this can be used with now or in the future. 

Thank-you!

**Comment by niklasr22** [comment]
Hello, thanks for reaching out and for appreciating the open source aspect.
Is it possible that you are using a MacBook Pro with an M1 (not Pro, not Max) with a 13" display and touchbar? BrightIntosh can't support this device as it isn't equipped with Apple's XDR technology. Only MacBook Pros that are currently available and have a built-in XDR display can be used with BrightIntosh. Additionally there is support for Apple's Pro Display XDR.

The app store description always contained a list of supported device models. The current description is the following:

```
This open-source application makes use of HDR content to increase the maximum brightness of your MacBook Pro for any app!
The app provides various settings like brightness levels, shortcuts and automations to make your experience as convenient as possible.

Supported devices are:

- MacBook Pro M3 from 2023 (Model Identifiers: Mac15,3, Mac15,6, Mac15,7, Mac15,8, Mac15,9, Mac15,10, Mac15,11)
- MacBook Pro M2 14" / 16" from 2023 (Model Identifiers: Mac14,5, Mac14,6, Mac14,9, Mac14,10)
- MacBook Pro M1 14" / 16" from 2021 (Model Identifiers: MacBookPro18,1, MacBookPro18,2, MacBookPro18,3, MacBookPro18,4)
- Pro Display XDR

Good indicators are the following two questions: Does the display of your MacBook have a notch, and does it say MacBook Pro on the underside of your device?
```

![image](https://github.com/niklasr22/BrightIntosh/assets/75939868/91519f2e-167a-4afd-965c-306b964c07b9)

I don't know how I can make it even clearer which devices are compatible. If you have an improvement, please share it. Thanks for your understanding!
