### ISSUE TITLE
No icon in status bar and dock don't make appear the "app is open dot" but it works (App Store)

### ISSUE THREAD

**Issue by Ostefanini** [niklasr22/BrightIntosh#153]
Hello,
I've downloaded the app from the app store.
The applications works if I launch it via CLI: `/Applications/BrightIntosh.app/Contents/MacOS/BrightIntosh` or if clicked once from the dock. To stop it I must control + c in the launching terminal (in CLI) or via Activity Monitor.

I have nothing in the status bar and no settings window appears in theses launching scenarios.

I have a macbook pro m3 pro 16 inch with the notch and the mention "Macbook PRO" under it. It runs MacOS 14.5

**Comment by niklasr22** [comment]
Hi,
thanks for reaching out. Is it possible that the entire status bar on the right of the notch is filled with other icons?
Maybe we should add a context menu that would allow access to the settings window when BrightIntosh is added to the dock..

**Comment by Ostefanini** [comment]
Screenshot of the right of my notch. For me there is still place on the left.
Still, there is no activation toggle in System preferences -> Control center -> 

<img width="675" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/8016962/8ce24951-3634-42b7-8a11-efd771bc695f">

I have absolutely no UI from brightintos, except the icon I've added in the dock but does absolutely nothing.

**Comment by niklasr22** [comment]
Thanks for sharing. I have never encountered this problem. I will look into it.
You aren't using apps that extend/alter the status bar (like Bartender, Barbee, etc.), right?

**Comment by Ostefanini** [comment]
You get me on the way ! I've disabled some of my app pined in the status bar and I see the light in it 🤣 (the icon appears and works fine).

I'll make some room for Brightintosh then, but accessing the settings UI from the main app icon could be really appreciated !

**Comment by Ostefanini** [comment]
You get me on the way ! I've disabled some of my app pined in the status bar and I see the light in it 🤣 (the icon appears and works fine).

I'll make some room for Brightintosh then, but accessing the settings UI from the main app icon could be really appreciated !
