### ISSUE TITLE
Stops working after getting back from sleep mode

### ISSUE THREAD

**Issue by diego351** [niklasr22/BrightIntosh#155]
After some time and getting back from sleep mode the increased brightness feature stops working. Need to "Deactivate" and "Activate" it to work again.

I'd like it to work consistently until I manually turn it off.

settings: 
<img width="474" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/1809191/7864e81b-5931-44d1-8c7a-a0b0584fe484">

**Comment by niklasr22** [comment]
Hi, thanks for reaching out. Do you have an estimate after how much time this happens? And do you have an external monitor connected during this period?

**Comment by diego351** [comment]
Hi! Thanks for fast reply! Yes, I do have an external monitor connected, hmm I'd need to test how much time it needs, usually happens when I turn it on, work for a couple hours, enter sleep mode without closing lid and open it up after some time, like an hour or so. Don't know the minimum time but I can pay attention to it and let you know. 

Nice software mate btw, works very well outside even when it's very sunny.

**Comment by niklasr22** [comment]
Thanks you! I can reproduce the issue and will work on a fix.

**Comment by diego351** [comment]
Perfect! Thank you, can I ask you to let me know after it's done and released so I can check? I'd appreciate that :)

**Comment by niklasr22** [comment]
Sure :)

**Comment by niklasr22** [comment]
I submitted a new version of BrightIntosh, but the App Store release will take a few hours because of the review process.

**Comment by niklasr22** [comment]
The update is now available through the App Store.

**Comment by diego351** [comment]
Just installed an update, will test it heavily and post the result. Thank you!

**Comment by diego351** [comment]
Works perfectly, thank you very much. I appreciate fast and effective reaction!

**Comment by niklasr22** [comment]
Great, thanks for the feedback!
