### ISSUE TITLE
Flash Calibration 

### ISSUE THREAD

**Issue by JayChen078** [niklasr22/BrightIntosh#157]
Hello there - 

When I first purchased & used the program, every time I would activate the "increased brightness", the screen did this sort of flash & fade, it seemed like gamma, bloom, or color calibration to me, only lasted like 2-3 seconds.

I haven't updated the app, nor made any changes to it. However, I noticed that this functionality doesn't exist anymore, when I activate full brightness, the screen no longer flashes and fades. I'm not significantly concerned, I mean the brightness itself is still activated and all - just wasn't sure if the loss of this was the application finally adapting to the display, or if I might've damaged the liquid XDR display itself.

**Comment by JayChen078** [comment]
A little update - I went into display settings, I changed the preset of the display to Apple 600-nits, and the flash happened, but it never faded (looks like a very high gamma setting basically). When I changed it to Apple XDR 1600 nits - no flash, no fade, just simply increased brightness. 

Still unsure where that functionality came to, or why it disappeared, wanted to make sure I didn't crap out my display since it's literally a week old.

**Comment by niklasr22** [comment]
Hi, thanks for reaching out. It doesn't always fade and it often only fades on bright spots. If i toggle it multiple times in a short time it doesn't fade, if i wait longer it does. I don't know what the exact reasons for this behavior are but it's how macOS controls the display panel. Unless everything is working and looking fine your display should be fine. The OS is in full control over the display.
