### ISSUE TITLE
A white pixel on the left edge of my screen

### ISSUE THREAD

**Issue by J-An-dev** [niklasr22/BrightIntosh#164]
Hi there,

I am running on BrightIntosh with v2.2.2 version. Whenever I connect or disconnect my mac to a monitor, I can notice a white pixel pops up on the left edge of my mac. It's really no biggie but still would love to see any way to fix it. Thanks.

Best,
J.

<img width="51" alt="Screenshot 2024-08-23 at 8 07 47 AM" src="https://github.com/user-attachments/assets/fe4c4773-606b-4782-b87b-c4b1a6aef05d">

**Comment by niklasr22** [comment]
Thanks, for reporting. I could reproduce the issue on a 16" MacBook but not on an 14" MacBook. I will fix it asap.

**Comment by J-An-dev** [comment]
> Thanks, for reporting. I could reproduce the issue on a 16" MacBook but not on an 14" MacBook. I will fix it asap.

Yeah, same here. Mine is a 16-inch Macbook Pro with M3 Pro chip.

**Comment by niklasr22** [comment]
I released [v2.2.3](https://github.com/niklasr22/BrightIntosh/releases/tag/v2.2.3) which should fix the issue. Please let me know if it doesn't. It will take a few hours until the update is available through the App Store.

**Comment by J-An-dev** [comment]
Just got a chance to upgrade via App Store. It works perfectly fine now with v2.2.3. Amazing! Thanks for the quick response.
