### ISSUE TITLE
Add support for different App Store accounts

### ISSUE THREAD

**Issue by BluCreatr** [niklasr22/BrightIntosh#168]
Hi! thanks for making this app! Can we add support for multiple App Store accounts? 

As a family, Brightintosh turns off when I switch App Store accounts. Perhaps once the cookie for an authenticated account authorizes the local device, we can simply keep that to enable Brightintosh when switching to another user? Thanks!

**Comment by niklasr22** [comment]
Hi, did you buy BrightIntosh via the in-app purchase? If so, I have just enabled family sharing for it. Does this solve your problem?
