### ISSUE TITLE
Can't sign in to apple id to pay after free trial

### ISSUE THREAD

**Issue by LucasBeiknejad** [niklasr22/BrightIntosh#173]
I downloaded the app months ago when it was free (there was nothing about a trial at that time). Now the app says my trial has ended, but i can't login to pay for the software. It keeps reopening the login window each time i type in my password. I have tripe checket that i am writing the correct password. Also tried to reinstall the app.

https://github.com/user-attachments/assets/23b52959-413a-4c12-b60e-5e4263e91ac8

**Comment by niklasr22** [comment]
I'm very sorry for the inconvenience. This should not happen and as you got BrightIntosh when it was free you shouldn't have to pay for it. Could you please try rebooting your MacBook as this helped before with such problems.

**Comment by LucasBeiknejad** [comment]
Hi Niklas, thank you very much! After restart the app is now working again :)
