### ISSUE TITLE
[BUG] I see a white dot on the left side of screen

### ISSUE THREAD

**Issue by donghun-choi** [niklasr22/BrightIntosh#188]
Literally, I see a white one pixel dot on the right side of screen. Which is even seen on screenshot. It disappears when i turn off the program. When I turn on the program again, it reappears immediately. When i logout or reboot the system and turn on the program, after some amount of time later it appears. but I don't know the exact conditions. However, it does not appear immediately after running the program. And also i cannot see it on the lock screen.

<img width="1512" alt="Screenshot 2024-11-12 at 9 26 06 PM" src="https://github.com/user-attachments/assets/1c02db0d-d6ed-4737-ab0b-af5745593f66">

<img width="281" alt="Screenshot 2024-11-12 at 9 30 17 PM" src="https://github.com/user-attachments/assets/ecf807a8-2a88-4eed-906b-48900ea07a9e">

you should look carefully! it is only one white dot on the left side of screen. i think it moves a little down compare to last time, but i am not sure.

**Comment by niklasr22** [comment]
Hello, thanks for reaching out. The white pixel is needed for BrightIntosh to work, but normally it should be positioned in the upper left corner of the screen. ([More](https://brightintosh.de#background)).

Which version of BrightIntosh are you running and do you use an external monitor with your Mac?

**Comment by donghun-choi** [comment]
Oh sorry for not reading the instructions
I am really sorry
Also apologize for not including the BrightIntosh report. I think it was deleted while including screenshots :c

BrightIntosh Report:
OS-Version: Version 15.1 (Build 24B83)
Version: BrightIntosh SE v3.3.0
Model Identifier: MacBookPro18,3
Original Purchase Date: 2024-10-04 04:05:04 +0000
Original App Version: 3.2.2
Transaction for App Version: 3.3.0
Transaction Environment: Production
Unrestricted user: true
Trial: Start Date: 2024-10-04 04:05:04 +0000 Current Date: 2024-11-13 13:40:20 +0000 Remaining: 0
Screens: ["Built-in Retina Display"]


I am not using any external monitor

Thank you

**Comment by niklasr22** [comment]
No worries :) 
I will try to reproduce the issue and come up with a fix.

**Comment by niklasr22** [comment]
I found some issues regarding the white pixel, but couldn't reproduce your problem without changing screen resolutions and stuff like that. Nevertheless the positioning should now work better. I’ll release version 3.5.1 with the fix soon. If the issue persists, feel free to reopen this issue. Thanks again for reporting it. :)

**Comment by donghun-choi** [comment]
Sound great! Thank you :D

**Comment by niklasr22** [comment]
That's a good point, I never thought about that, thank you! I will try it out :)
