### ISSUE TITLE
App uses much more RAM than BetterDisplay

### ISSUE THREAD

**Issue by YousufSSyed** [niklasr22/BrightIntosh#23]
BetterDisplay has much more features and uses 30-60MB of ram while BrightIntosh uses 130-180MB. I know this is a FOSS app which I really appreciate, I just recommend you to optimize that since that is a lot of RAM for an app that just changes the brightness scale.

**Comment by niklasr22** [comment]
Thanks for noticing that issue. It is fixed with the newest release [(v1.0.9)](https://github.com/niklasr22/BrightIntosh/releases/tag/v1.0.9)
