### ISSUE TITLE
SDR Videos do not get extra brightness applied

### ISSUE THREAD

**Issue by SUPERCELLEX** [niklasr22/BrightIntosh#28]
When watching a video with BrightIntosh enabled, the video will have SDR brightness unless the mouse cursor is moving, this occurs in Apple apps like Safari and QuickTIme, other apps like VLC, Chromium and FireFox are not affected. This appears to be a quirk about how Apple things specifically handles color profiles that fights with BrightIntosh.

**Comment by SUPERCELLEX** [comment]
I don't know how to use GitHub, how do I tag issues?

**Comment by SUPERCELLEX** [comment]
Debugging, it seems HDR videos don't either, on all apps, including non-Apple ones. It seems the Apple behavior between HDR and SDR doesn't change, so Apple software still engages the HDR anti-clip on SDR content
It seems to fix this you'd need to find a way to kill the HDR anti-clip, either only on SDR or just by telling the user not to watch HDR with BrightIntosh enabled unless you want videos clipping.

**Comment by niklasr22** [comment]
Thanks for the detailed check! I think increasing the brightness of SDR videos makes sense, but I am not sure about HDR videos yet. That clipping destroys the experience... 

(Issues can be tagged with #x whereas x is the corresponding "id"😉)

**Comment by niklasr22** [comment]
Related to #4

**Comment by SUPERCELLEX** [comment]
The funny thing is, the system works close to flawlessly now on everything BUT Apple-vendored apps, so on Chrome HDR will not clip and SDR's brightness is managed properly, but on Safari everything is broken

**Comment by SUPERCELLEX** [comment]
Moving the mouse on an HDR video WILL clip it, on both non-Apple and Apple apps, however with Chromium and Firefox SDR does not exhibit this seemingly anti-clip calibration on Chrome/Firefox
In this sense Apple is actually doing it _more_ correct by enforcing that SDR stays with SDR's display properties, but it breaks apps like BrightIntosh in doing so
Also I meant like labeling bug vs feature, I'm not good at GitHub tbh
