### ISSUE TITLE
Menu closes when Gamma adjusted

### ISSUE THREAD

**Issue by SUPERCELLEX** [niklasr22/BrightIntosh#31]
Functionality is perfect on 1.0.10, however one thing I noticed is that the system will close your app's menu after one gamma adjustment. 2 ways to improve this UX flow, either get Aqua not to close your menu when clicking Gamma adjustment buttons, or just bind a shortcut to Gamma adjustment. Also maybe call this 1.1 cause all the functionality works as well as Vivid and that's kinda major.

**Comment by SUPERCELLEX** [comment]
Gamma _might_ be a debug issue I just realized but honestly it's pretty functional. Some programs use a slider (BetterDisplay) to adjust gamma, however that comes with issues of being a pain to implement instead of just telling macOS to give you a menubar icon and a menu

**Comment by SUPERCELLEX** [comment]
I haven't touched OSX development but lemme see if i can just bind something to gamma up and down in hotkeyutils

**Comment by SUPERCELLEX** [comment]
oh I've been building as debug release isn't even supposed to see the gamma modification menu items LMFAO

**Comment by niklasr22** [comment]
Thanks for all your efforts! Currently those gamma adjustment buttons are only visible in the debug build and not in the release build, but i think it wouldn't be bad if the user could modify the gamma value.

**Comment by SUPERCELLEX** [comment]
I added a shortcut for - and = to lower and raise gamma respectively, trying to get the modifier keys to be cmd+opt instead of cmd and I'll PR it... somehow, considering I've never touched GitHub in my life either, or I can PR now but just cmd+-/= conflicts with Finder

**Comment by niklasr22** [comment]
Nice! Another possibility could be using the actual brightness keys with a modifier but i'm not sure if apple allows this

**Comment by SUPERCELLEX** [comment]
Nope welcome to debug hell it's not registering the shortcuts I added

**Comment by SUPERCELLEX** [comment]
I'm an idiot I forgot to change the key code

**Comment by SUPERCELLEX** [comment]
> Nice! Another possibility could be using the actual brightness keys with a modifier but i'm not sure if apple allows this

Xcode only has kVK for VolumeUp and VolumeDown, I know Lunar did hijack the brightness keys and so did BetterDisplay, so I know BrightIntosh _could_

**Comment by SUPERCELLEX** [comment]
It also has function keys which _could_ be how those 2 apps did it but it could also not be

**Comment by SUPERCELLEX** [comment]
huh, now hotkeyutils is reading every key as toggle brightintosh

**Comment by SUPERCELLEX** [comment]
I am way over my head rn I can't see why the hotkeys are calling toggle brightintosh when it should be toggling increase/decreaseGamma

**Comment by SUPERCELLEX** [comment]
Default behavior in 1.1 is perfect however, so I could just close this issue as "eh only gets seen as debug should be fine"

**Comment by niklasr22** [comment]
That's fine. Take your time, there is no need to rush :)

**Comment by niklasr22** [comment]
Actually i think i did an error where the event gets handled. I don't think the right hotkey id is retrieved.

**Comment by SUPERCELLEX** [comment]
I THOUGHT THAT WAS IT AFTER A LITTLE KEKW

**Comment by SUPERCELLEX** [comment]
there we go now it works

**Comment by SUPERCELLEX** [comment]
Obsolete as of https://github.com/niklasr22/BrightIntosh/issues/49#issue-1868529743
