### ISSUE TITLE
Can updates be installed without downloading a new DMG for each new update?

### ISSUE THREAD

**Issue by YousufSSyed** [niklasr22/BrightIntosh#36]

**Comment by SUPERCELLEX** [comment]
Possibly there could be a library lying around to automate the process of a helper app for autoupdates, I'll have to check it out
A good middle ground would be for the button to just download a DMG, considering you're using the app and it sends you to a link, that link could just be... the download for the new version

**Comment by niklasr22** [comment]
Integrating [Sparkle](https://sparkle-project.org/) could be a solution.

**Comment by niklasr22** [comment]
The new [release](https://github.com/niklasr22/BrightIntosh/releases/tag/v1.2.0) includes this feature.
