### ISSUE TITLE
OS support (Monterey)

### ISSUE THREAD

**Issue by fdawans** [niklasr22/BrightIntosh#39]
Hello,
I couldn't install the app on Monterey.
I don't know if it's on purpose or not.
I guess I should update to Ventura.
Thank you for your help,

<img width="251" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/53601011/0fb5738a-eaa6-4645-ac33-e2a05fb1281e">

**Comment by niklasr22** [comment]
[Version 1.1.1](https://github.com/niklasr22/BrightIntosh/releases/tag/v1.1.1) should be runnable on MacOS Monterey.

**Comment by fdawans** [comment]
Thank you, it's working!!
