### ISSUE TITLE
Hide the HDR pixel

### ISSUE THREAD

**Issue by niklasr22** [niklasr22/BrightIntosh#41]
A bright white pixel is visible near the lower left corner of the screen.

To do: hide it better

Possible ways:

- Move the `OverlayWindow` to a more appropriate spot
- Change the alpha value of the `OverlayWindow`

**Comment by SUPERCELLEX** [comment]
One could possibly hide the pixel under the notch, for as pretty much all macs I know that have HDR minus the ProDisplay and other external monitors also have a notch. I can test if that works on my system quite quick

**Comment by SUPERCELLEX** [comment]
nope nvm Apple apparently disallows that under the assumption you want your program to show its window 
<img width="877" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/44790931/016359af-8df5-4919-9102-b55052330382">
I'm seeing if I can refactor it to be independent of its window

**Comment by SUPERCELLEX** [comment]
switching from visibleframe to frame has no effects, and allows me to hide under the notch

**Comment by niklasr22** [comment]
Moving it up to the upper left corner should work because of the rounded corner of the macbook display.

**Comment by SUPERCELLEX** [comment]
yeah that would work too... if I can figure out _how_ exactly

**Comment by niklasr22** [comment]
Setting the position can be done with `setFrameOrigin` and you can use the origin of the screen plus the hight of the screens frame as an additional y offset.
