### ISSUE TITLE
Add the ability to modify the "Activate" shortcut

### ISSUE THREAD

**Issue by gregsh** [niklasr22/BrightIntosh#60]
Thanks for the app!

Please make the "Activate" shortcut configurable.

The current shortcut hijacks my IntelliJ IDEA `Navigate` shortcut. 

It cannot be altered by system tools  - `Settings -> Keyboard -> Shortcuts` does not work for menu bar apps.

**Comment by niklasr22** [comment]
This feature is part of version [v1.3.0](https://github.com/niklasr22/BrightIntosh/releases/tag/v1.3.0)
