### ISSUE TITLE
Crypto donations?

### ISSUE THREAD

**Issue by ricardo-rp** [niklasr22/BrightIntosh#61]
I was about to purchase the 'vivid' app, so I just decided to donate the full amount I was going to pay for that license to this project. Big props to you for making it open source!

I'd like to avoid creating a paypal account for this. Crypto donations are more convenient for me. Do you by any chance accept USDC or some other form of cryptocurrency? If you do, please consider adding this to the project page. 
Thanks again!

**Comment by niklasr22** [comment]
Thanks for your support and willingness to donate! I completely understand your preference for cryptocurrency donations, but as of now, I haven't found a suitable crypto payment processor for the project yet. I think PayPal offers an option for credit/debitcard donations without creating an account but I can understand if thats not an option for you. Thanks again, I truly appreciate your consideration.

**Comment by ricardo-rp** [comment]
I went through the trouble to donate using paypal. I think whoever makes open source deserves some recognition. Please keep maintaining this while you can

**Comment by niklasr22** [comment]
Thank you so much! Your support means a lot! It's great that people care about this project and its open-source aspect. Thanks again!
