### ISSUE TITLE
Brightness bar in menu dissapears when brightness toggle shortcut removed.

### ISSUE THREAD

**Issue by SUPERCELLEX** [niklasr22/BrightIntosh#78]
Steps to reproduce:
Remove the 'Toggle Brightness' shortcut and do not set a new one
Observe how the brightness bar is now non-existant
Normal behavior
<img width="210" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/44790931/31257378-d8f6-48c8-b170-12fd8387fa56">
<img width="200" alt="image" src="https://github.com/niklasr22/BrightIntosh/assets/44790931/8b17ada0-cfb2-4617-a0ba-b33f386e21c6">

**Comment by niklasr22** [comment]
Thanks for reporting
