### ISSUE TITLE
Report a bug where the GUI disappears for non-Apple App Store download versions

### ISSUE THREAD

**Issue by UPennftz** [niklasr22/BrightIntosh#83]
I'm using a non-Apple App Store download version, but after I checked Launch on Login, clicked Check for Updates, and turned on Auto Check for Updates. The software interface disappears into thin air, but 1000 nits brightness and shortcuts (command+option+M/N/B) work fine. When I use Apple Store version, this bug disappears. I think the problem might be in the Auto-Check-Updates.

A heartfelt expression of gratitude for your selflessness.

device:
M2 Pro
macOS Sonoma 14.1

**Comment by niklasr22** [comment]
Hi, thanks for reporting the bug and for your kind words. I haven’t been able to reproduce the behavior you described yet. Can you please let me know which app version you were using? Also, were you able to reproduce this issue multiple times?

**Comment by UPennftz** [comment]
The version in question is the non-App Store version of 1.4.1 (https://github.com/niklasr22/BrightIntosh/releases/download/v1.4.1/BrightIntosh_v1.4.1.dmg). 

I have now uninstalled that version and re-downloaded version 1.4.1 from the Apple App Store. The problem has not recurred with this version. So maybe checking that the non-app shop version (1.4.1) has more features than the Apple app shop version (1.4.1) might help with debugging.

The problem is that after the computer is switched on and automatically launches the non-app shop version of BrightIntosh, the status bar icon suddenly disappears after using the computer for 1 minute or maybe more. Clicking on the app icon from the Launchpad and exiting the app from the Activity Monitor does not open the app interface again, but shortcut switching and adjusting the brightness still works at this point, which is why I'm guessing that the disappearance of the graphical interface may be caused by an auto-detect update to a non-app shop version.

**Comment by UPennftz** [comment]
Ignore the scene if you can't reproduce it. Because it could be due to my individual equipment differences.
