### ISSUE TITLE
Sound bug when settings window is opened

### ISSUE THREAD

**Issue by lucaschindler** [niklasr22/BrightIntosh#84]
When adjusting the brightness slider in the menu bar while the BrightIntosh settings window is opened, there is a strange sound.

I have the 14" M1 Pro model.

**Comment by niklasr22** [comment]
Thanks for reporting. I successfully reproduced this behaviour and will fix it in the next update.

**Comment by lucaschindler** [comment]
Thanks! That was pretty fast!
