### ISSUE TITLE
Brightintosh only applying to upper portion of display

### ISSUE THREAD

**Issue by andrewjosephlehmann** [niklasr22/BrightIntosh#88]
For some reason when I activate Brightintosh the brightness only increases above the dock on my M1 Pro MacBook Pro. ![image](https://github.com/niklasr22/BrightIntosh/assets/64662786/5a652938-5c0a-4025-8402-5b178ae5cbb1)

**Comment by niklasr22** [comment]
Hi, thanks for reporting this. What version of BrightIntosh and MacOS are you using?
And are you using any other tools such as similar software or window managers that might interfere?

**Comment by andrewjosephlehmann** [comment]
I am currently using Brightentosh version 1.4.2. To my knowledge, I don't have any software that would conflict with BrightIntosh. Let me know if I can run any terminal commands to diagnose the issue. :)

**Comment by niklasr22** [comment]
I have reproduced the problem. Are you using the 'Increase brightness using an overlay technique' option in the Advanced tab of BrightIntosh and is your MacOS Dock always visible?

If so, I would recommend disabling this overlay technique option as it doesn't really improve anything.
But I will look into fixing this mode for always visible macOS docks.

**Comment by andrewjosephlehmann** [comment]
Turning off 'Increase brightness using an overlay technique' appears to have fixed the problem. I must have inadvertently activated it without realizing it was causing this error. Thank you!
