### ISSUE TITLE
Should the BrightIntosh icon be updated everywhere?

### ISSUE THREAD

**Issue by YousufSSyed** [niklasr22/BrightIntosh#92]
I see the icon is in a square on Mac but on the repo and the website the icon is by itself.

**Comment by niklasr22** [comment]
Yes, the icon is enclosed by this square because of Apple's design guidelines. I think the readme of this repo should be updated to match the app icon. As for the website, I'm not sure it looks very good.

**Comment by niklasr22** [comment]
The icons are now updated both in the readme and on the website
